### ISSUE TITLE
No such file or directory(base) 

### ISSUE THREAD

**Issue by xkommando** [HebiRobotics/QuickBuffers#24]
hi,
im manually running quickbuf with protoc 3.8 on ubuntu20, and got this error:
```
protoc-3.8.0-linux-x86_64.exe --quickbuf_out=java8_optional=false: market_events.proto
: No such file or directory(base) 
```
i followed the instruction and put the quickbuf code in the same dir as `protoc-3.8.0-linux-x86_64.exe` and added it to path.
could you give a bit more detailed instructions on how to manually run it? thanks!

**Comment by ennerf** [comment]
Thank you for reporting a problem with the documentation. It was missing the `<output_directory>` option. The following should work:

`protoc-3.8.0-linux-x86_64.exe --quickbuf_out=java8_optional=false:. market_events.proto`

**Comment by xkommando** [comment]
thanks!
