### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by spheenik** [HebiRobotics/QuickBuffers#40]
Hi guys,

seems like a really cool project!

I am the creator of [Clarity](https://github.com/skadistats/clarity), a parser from replay files that the game Dota2 generates. As such, I have to work a lot with Protobuf (2), since the files rely on them as a base. I have done as much as I could to optimize the code, for example injecting a small [ZeroCopy](https://github.com/skadistats/clarity-protobuf/blob/master/src/main/java/com/google/protobuf/ZeroCopy.java) into their package, to allow me to extract the content of an underlying `ByteString` without making a copy, or to create an `ByteString` from a `byte[]` I supply without copying.

When I read the benchmarks you post, it seems I just have to put some work in to see how much performance this could bring.

Some questions:

1. Will I be able to do what the above mentioned `ZeroCopy`-utility does, which means getting at the data of a protobuf `bytes`-field without copying, and creating one without copying?
2. Do I understand correctly, that you build your classes with a `protoc` plugin?
3. I still have to use Protobuf 2.6, ([Protobufs here](https://github.com/skadistats/clarity-protobuf/tree/master/src/main/proto)), will I be able to use your project, and in that case, what version of `protoc` should I use? 

Anyway, way to go, I love it!

**Comment by ennerf** [comment]
Hi! Yes, that is already supported out of the box. The fastest way to read log files would be to open it as a memory mapped file and use a `DirectSource` to read directly from there without any temporary buffers. 

I think the minimum version I tested is protoc 3.9.4 or so, but pretty much anything should work. You can also download pre-built binaries from the [Download](https://hebirobotics.github.io/QuickBuffers/download.html) page and just use the bundled protoc. There is also a `replace_package` option that can be useful if you want to try it out without colliding with Protobuf-Java files, e.g.,

```sh
protoc-quickbuf --quickbuf_out=${quickbuf.options},replace_package=protoc=quickbuf:<outputDir> <protoFiles>
```
If you are mainly consuming existing protobuf files you may also want to set `input_order=number`.

**Comment by spheenik** [comment]
Is there a way to just get the plugin and use the protoc supplied from the operating system?

```
➜  ~ protoc --version
libprotoc 3.21.12
```

**Comment by ennerf** [comment]
`protoc-quickbuf` is just a renamed `protoc`. All you need to do is get `protoc-gen-quickbuf` on the PATH and then execute protoc. The package automatically handles the setup, but you can also get the raw plugin from https://github.com/HebiRobotics/QuickBuffers/releases

`protoc --quickbuf_out=${quickbuf.options},replace_package=protoc=quickbuf:<outputDir> <protoFiles>`

**Comment by spheenik** [comment]
All right, I'm going to give it a try. Thanks for the quick responses!

**Comment by ennerf** [comment]
I deleted that section from the Readme because I thought it was unnecessary, but maybe I should add it back :)

https://github.com/HebiRobotics/QuickBuffers/commit/baa072614e604af9d29baa14f259b8b15d3f1732#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L98-L124

**Comment by spheenik** [comment]
Ok, I'm gonna try to get it working with the plugin.tar.gz installed in `/opt` somehow.
If all will work out, I can still make a proper package for my OS. (Arch)

**Comment by spheenik** [comment]
Ok, I got it to execute, but it stumbles over messages nested inside of other message.
Small example:

```protobuf
message Outer {
  message Inner {
    optional int32 id = 1;
  }
  repeated Inner inners = 1;
}
```

Commandline:
```
protoc-quickbuf --quickbuf_out=input_order=number:../../java test.proto
```

yields

```
--quickbuf_out: java.lang.NullPointerException: Unable to resolve type id: .Outer.Inner
        at us.hebi.quickbuf.generator.Preconditions.checkNotNull(Preconditions.java:232)
        at us.hebi.quickbuf.generator.TypeRegistry.resolveMessageType(TypeRegistry.java:88)
        at us.hebi.quickbuf.generator.TypeRegistry.resolveJavaTypeFromProto(TypeRegistry.java:78)
        at us.hebi.quickbuf.generator.RequestInfo$FieldInfo.getTypeName(RequestInfo.java:520)
        at us.hebi.quickbuf.generator.FieldGenerator.<init>(FieldGenerator.java:706)
        at us.hebi.quickbuf.generator.MessageGenerator.lambda$new$17(MessageGenerator.java:816)
        at java.base@17.0.6/java.util.ArrayList.forEach(ArrayList.java:1511)
        at us.hebi.quickbuf.generator.MessageGenerator.<init>(MessageGenerator.java:816)
        at us.hebi.quickbuf.generator.CompilerPlugin.handleRequest(CompilerPlugin.java:96)
        at us.hebi.quickbuf.generator.CompilerPlugin.handleRequest(CompilerPlugin.java:67)
        at us.hebi.quickbuf.generator.CompilerPlugin.main(CompilerPlugin.java:62)
```

Am I doing something wrong?

**Comment by ennerf** [comment]
Interesting. I've definitely tested many different kinds of nested and imported messages, but I'm not sure whether I ever tested a proto file without a package. Can you add a package identifier?

I'll make a note of that.

**Comment by spheenik** [comment]
After adding a package, it works.

My source [GameTracking-Dota2](https://github.com/SteamDatabase/GameTracking-Dota2/blob/master/Protobufs) extracts the definitions from the game's binaries. Most certainly they are unable to extract it, so it's just left out.

I'll just add a package definition to all my protobufs, and I guess I will be fine.

**Comment by spheenik** [comment]
Working good so far, I managed to build `clarity-protobuf` using QuickBuffers, now I "only" have to adapt it's main code.
Small observation I had, where you can probably squeeze out some cycles:

For a protobuf enum, you generate a `forName(final CharSequence value)` where you compute the length, and then only compare with the ones that have the same length.

Any reason you need to have a `CharSequence` and not a `String` as a parameter? 
I ask, because I learned a while ago that if you do a `switch` statement where the cases are `Strings`, then java does optimize this on compilation by doing a `hashCode()` first, and comparing this to all the precomputed `hashCode()` from the cases.

So even if you need to use `CharSequence`, maybe you can (in `ProtoUtil.isEqual()`) by comparing their `hashCode()` first, and if unequal skip iterating over them.

**Comment by ennerf** [comment]
The library has a zero allocation constraint, so I can't use immutable Strings in the API. A `CharSequence` parameter also works with a mutable `StringBuilder`.

I think you're referring to the JSON parsing? It's possible to do a switch statement on the hash of the String, but it should be generating different code depending on the number of cases and similarities. You're using the binary parser though, right?

**Comment by spheenik** [comment]
Yes, I am using the Binary Parser.
I was just taking about the `forName()` function that you generate for a protobuf enum.
It's probably not used on a very hot code path anyway, so optimizing here is only for the perfectionists.

Btw:
```java
    public static RepeatedByte newInstance(byte[] initialValue) {
        return newEmptyInstance().copyFrom(initialValue);
    }
```
The only constructor `RepeatedByte` offers is one that copies the data.
Could we have one that I gift the byte array I have to?

**Comment by ennerf** [comment]
That would not be safe because the `byte[]` instance is handled internally by the `RepeatedByte` class and may change when data is appended. However, you can pre-size the internal array and store your data in there instead  `array[] = bytes.setLength(n).array()`.

**Comment by spheenik** [comment]
Hmm, I understand, I used the `ZeroCopy.wrap()` function to construct a protobuf-java `ByteString` from a `byte[]` without copying.

For example, I have the following code:
```java
                    return Demo.CDemoPacket.newInstance()
                            .setSequenceIn(source.readFixedInt32())
                            .setSequenceOutAck(source.readFixedInt32())
                            .setData(ZeroCopy.wrap(readPacket(source)))
                            .build();
```
`readPacket(source)` returns a `byte[]`. `setData()` receives a `ByteString` and `ZeroCopy.wrap()` is there to construct one from the array I have without copying. Right now, your API for `setData()` wants a `byte[]` but makes a copy as well, and it seems there is no way around it. 

That's why I said "gift". I want it to take the array, knowing full well that I cannot use it afterwards, but I want to prevent copying.

**Comment by spheenik** [comment]
> That would not be safe because the `byte[]` instance is handled internally by the `RepeatedByte` class and may change when data is appended. However, you can pre-size the internal array and store your data in there instead `array[] = bytes.setLength(n).array()`.

And to add, presizing the array beforehand is not really an option for me, since then all the array producing code would have to know it will end up in a `RepeatedByte` and act accordingly.

**Comment by ennerf** [comment]
I guess I could add a `RepeatedByte::setReference(byte[] array, int length}` that replaces the internal array.

**Comment by spheenik** [comment]
> To the best of my knowledge that is the fastest way to do it. It is not in the hot path though, so I have not verified it excessively.

It would probably be slightly faster if in `isEqual(CharSequence a, CharSequence b)` you would compare their hashes before starting to iterate over them in the else-branch. But yeah, path is probably very cold, so not really needed.

**Comment by spheenik** [comment]
> I guess I could add a `RepeatedByte::setReference(byte[] array, int length}` that replaces the internal array. Let me know in case you find anything else.

I think that does not help, because the problem lies in `setData()` accepting only a `byte[]`.

**Comment by ennerf** [comment]
`setData` is just a convenience method. If you do `getMutableData()` you get more raw access.

**Comment by spheenik** [comment]
Ah, ok, yes, that would work.

**Comment by spheenik** [comment]
`getMutableData().setReference(myArray)` should be fine.

**Comment by spheenik** [comment]
Merke gerade, du kommst aus Österreich. Egal, machen wir trotzdem in Englisch weiter, für die Nachwelt ;-)

**Comment by spheenik** [comment]
It' almost 2am in Cyprus, enough for today!
Will continue on the migration tomorrow, I hope I have some performance-numbers tomorrow evening.

**Comment by ennerf** [comment]
Good luck with the migration tomorrow. I'm looking forward to see a comparison.

**Comment by ennerf** [comment]
I added fixes for your issues so far. Let me know if you encounter anything else and I can do another bugfix release.

**Comment by spheenik** [comment]
Good morning.
Thank you.
I do not see a way to `setInternalArray()` on a RepeatedByte though (in this [commit](https://github.com/HebiRobotics/QuickBuffers/commit/16eb4ac47150a2f0b414d0a776184dc456a04060). I might be missing something, as `RepeatedByte` is in my runtime.jar, but missing in your runtime sources, so maybe it's autogenerated?

**Comment by ennerf** [comment]
I haven't done a release, so if you would like to use it you would have to run `mvn clean install` and then depend on the `1.1.1-SNAPSHOT` runtime. The messages can still be generated with the released `1.1.0` generator.

**Comment by spheenik** [comment]
And then, RepeatedByte will have the method? Just wondering how, from looking at the commit ;-)

**Comment by ennerf** [comment]
`RepeatedByte` is auto-generated from `RepeatedFloat` https://github.com/HebiRobotics/QuickBuffers/blob/develop/runtime/pom.xml#L96-L127

**Comment by spheenik** [comment]
Gotcha!

**Comment by ennerf** [comment]
It's easier to auto-generate, and `float` is the least likely one to have API collisions.

**Comment by spheenik** [comment]
`mvn install` of the current HEAD fails, because it's trying to gpg-sign `quickbuf-parent`.
Maybe you should move that to the `deploy` step?

**Comment by spheenik** [comment]
Another small thing:

I have the following code:
```java
return Demo.CDemoConsoleCmd.newBuilder()
                            .setCmdstringBytes(ZeroCopy.wrap(readPacket(source)))
                            .build();
```
`CDemoConsoleCmd` is defined like this:
```protobuf
message CDemoConsoleCmd {
	optional string cmdstring = 1;
}
```
Protobuf offers an API to directly set the contents of the string, if you have the bytes. 
Since you expose this as a `Utf8String`, is this the standard encoding used by protobuf for `string` fields?

**Comment by spheenik** [comment]
Ok, results are in, each is 10 round of parsing the same replay, to let the JVM properly warm up.

```
CSGO Protobuf:
total time taken: 3.322s
total time taken: 2.836s
total time taken: 2.838s
total time taken: 2.855s
total time taken: 2.846s
total time taken: 2.859s
total time taken: 2.856s
total time taken: 2.849s
total time taken: 2.858s
total time taken: 2.864s

CSGO QuickBuffers:
total time taken: 3.483s
total time taken: 2.791s
total time taken: 2.793s
total time taken: 2.794s
total time taken: 2.798s
total time taken: 2.782s
total time taken: 2.797s
total time taken: 2.791s
total time taken: 2.795s
total time taken: 2.796s

Dota 2 Protobuf:
total time taken: 1.353s
total time taken: 1.033s
total time taken: 1.023s
total time taken: 1.005s
total time taken: 1.008s
total time taken: 1.012s
total time taken: 1.01s
total time taken: 1.013s
total time taken: 1.011s
total time taken: 1.017s

Dota 2 QuickBuffers:
total time taken: 1.373s
total time taken: 1.043s
total time taken: 1.023s
total time taken: 1.022s
total time taken: 1.017s
total time taken: 1.025s
total time taken: 1.013s
total time taken: 1.019s
total time taken: 1.017s
total time taken: 1.006s
```

**Comment by spheenik** [comment]
Seems like especially the CSGO side benefits a little (this is because for CSGO, the replay does not contain Protobufs as a base, and to feed the rest of the parser the same data, I wrap it into Protobufs, which seems to be a tad faster.

On the Dota 2 side though, it seems they really are equivalent.

**Comment by spheenik** [comment]
When I switch to `input_order=quickbuf`, Dota 2 yields better results:
```
total time taken: 1.33s
total time taken: 1.022s
total time taken: 1.002s
total time taken: 1.002s
total time taken: 0.998s
total time taken: 0.998s
total time taken: 0.997s
total time taken: 0.989s
total time taken: 0.996s
total time taken: 0.993s
```

**Comment by ennerf** [comment]
Thanks. That seems like less of a difference that I'd expect. Can you give me a link to the source code?

> Since you expose this as a Utf8String, is this the standard encoding used by protobuf for string fields?

Yes, bytes are sent as utf-8. I'm considering adding a `setInternalArray` method there too, but haven't decided on it yet.

**Comment by ennerf** [comment]
And have you confirmed that parsing is actually the bottleneck here?

**Comment by spheenik** [comment]
Source is the main [Clarity project](https://github.com/skadistats/clarity) as well as the separate [Protobuf definitions](https://github.com/skadistats/clarity-protobuf).

Before we go in deeper, I will continue a bit on the benchmarking, because I just noticed that I ran my tests with JDK 8, and running them with 11 or 17 yielded a substantial speedup, so I have to run the old version against them first ;-)

**Comment by spheenik** [comment]
But before you search yourself blind, what I do from the top level, is, for each of the messages in the replay, call

https://github.com/skadistats/clarity-protobuf/blob/master/src/main/java/skadistats/clarity/wire/Packet.java#L32-L38

(This is still for the Google version, so in your case, it would call `parseFrom(byte[])` on the message.

**Comment by spheenik** [comment]
Results for JDK 17:
```
CSGO Protobuf:
total time taken: 3.201s
total time taken: 2.794s
total time taken: 2.705s
total time taken: 2.702s
total time taken: 2.688s
total time taken: 2.67s
total time taken: 2.662s
total time taken: 2.69s
total time taken: 2.671s
total time taken: 2.696s

CSGO QuickBuffers:
total time taken: 2.977s
total time taken: 2.832s
total time taken: 2.75s
total time taken: 2.754s
total time taken: 2.73s
total time taken: 2.729s
total time taken: 2.747s
total time taken: 2.747s
total time taken: 2.741s
total time taken: 2.731s

Dota 2 Protobuf:
total time taken: 1.233s
total time taken: 0.944s
total time taken: 0.923s
total time taken: 0.876s
total time taken: 0.922s
total time taken: 0.872s
total time taken: 0.869s
total time taken: 0.886s
total time taken: 0.889s
total time taken: 0.895s

Dota 2 QuickBuffers:
total time taken: 1.242s
total time taken: 0.921s
total time taken: 0.899s
total time taken: 0.873s
total time taken: 0.902s
total time taken: 0.862s
total time taken: 0.904s
total time taken: 0.863s
total time taken: 0.895s
total time taken: 0.86s
```

Seems like updating the JDK is always a good idea.
Previous results were JDK 8 for Dota, and 11 for CSGO.

**Comment by ennerf** [comment]
I'd be primarily interested in seeing how you are calling QuickBuffers because I assume that you are not using it in the most efficient manner. `Message::parseFrom` is a convenience method that has almost the same overhead as using Protobuf.

For reading log files you should be using a single source with a single message instance and calling `clearQuick` with `mergeFrom`. Here is an example [SbeBenchmark](https://github.com/HebiRobotics/QuickBuffers/blob/main/benchmarks/src/main/java/us/hebi/quickbuf/benchmarks/comparison/SbeBenchmark.java#L164-L172)

**Comment by spheenik** [comment]
> And have you confirmed that parsing is actually the bottleneck here?

A Dota 2 replay contains a lot of information, and Clarity "gets configured" by the caller to know what kind of data he wants to extract. Depending on that, Clarity has to do more or less work. The usecase the benchmarks are generated from is one where Clarity has to do *a lot* more than just reading protobufs. 

So it definitively is not the bottleneck.

**Comment by spheenik** [comment]
> I'd be primarily interested in seeing how you are calling QuickBuffers because I assume that you are not using it in the most efficient manner. `Message::parseFrom` is a convenience method that has almost the same overhead as using Protobuf.

Which is exactly what I do.
So basically, what I need to do is every time a Packet has to be parsed, try to reuse an instance of it and use `mergeFrom()`. I will look into how you did it in your benchmark.

**Comment by spheenik** [comment]
Question: Seems like a `RepeatedByte` keeps it's array when I call `clear()` on it, so when I later use its array, only up to `length()` may be used?

**Comment by spheenik** [comment]
Ok, I answered the last question myself, and it is "Yes" :-)

Anyway, I now have an instance cache, where whenever an instance of a `ProtoMessage` is to be parsed, I do the following:

```java
        public T parse(byte[] data) throws IOException {
            instance.clear();
            instance.mergeFrom(ProtoSource.newInstance(data));
            return instance;
        }
```
Speed seems to be roughly the same though, so I suspect that's because I have to construct a `ProtoSource` every time. Seems like the only way around would be if my [Source](https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/source/Source.java) would be a `ProtoSource` already, am I right?

**Comment by spheenik** [comment]
...and that would probably be a problem, because in the demo file, some packets are compressed, and this is indicated to me by an "instream flag". In the replay, the data is structured like this:

```java
        int rawKind = source.readVarInt32();
        final boolean isCompressed = (rawKind & getCompressedFlag()) == getCompressedFlag();
        final int kind = rawKind &~ getCompressedFlag();
        final int tick = source.readVarInt32();
        final int size = source.readVarInt32();
        // message data as protobuf, size bytes
```

so when I read the message, I do this:

```java
    public byte[] readFromSource(Source source, int size, boolean isCompressed) throws IOException {
        byte[] buf = new byte[size];
        source.readBytes(buf, 0, size);
        if (isCompressed) {
            return Snappy.uncompress(buf);
        } else {
            return buf;
        }
    }
```

and there's no way around that, other than writing a `ProtoSource` that you can indicate that the next x bytes are snappy-compressed data, which is not feasible, I guess.

**Comment by spheenik** [comment]
Well, at least, I will steal your `readVarInt32` method, if I may!

**Comment by ennerf** [comment]
Creating the source shouldn't be as much overhead as a message, but for uncompressed data you shouldn't need to copy the payload into a `byte[]` at all.

Decompression is probably going to be much slower than parsing Protobuf though. Can you upload a file that I can try something with? Which proto is at the top level and which one would be the inner payload?

**Comment by ennerf** [comment]
> Speed seems to be roughly the same though, so I suspect that's because I have to construct a ProtoSource every time. Seems like the only way around would be if my [Source](https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/source/Source.java) would be a ProtoSource already, am I right?

No, you can use the instance similarly to how you use the message instance. `ProtoSource::setInput(byte[])` resets it. You can also read into a `RepeatedByte` rather than creating a new `byte[]` every time.

None of that is going to solve the main issue of decompression though. One thing you could do is parallelize the decompression and then use a single thread for parsing all the raw bytes.

**Comment by spheenik** [comment]
Well that's complicated. At the end, a demo file is a little bit more complex than just a stream of messages whose type is known.
I'm not sure if you want to delve into this.

Because it is a stream of several messages, the type of the next message has to be encoded in the file. That's why I have to maintain maps of "kinds" to "message types", like this one [for the top level](https://github.com/skadistats/clarity-protobuf/blob/master/src/main/java/skadistats/clarity/wire/common/DemoPackets.java).

The demo file has a header, which is also specific to the game that produced it (Dota 2 before and after Source 2, and CSGO, all are different). After that it is a loop of:

```
loop {
   varInt32 kind (including a flag, whether the message payload is snappy compressed)
   varInt32 tick (starts at beginning of game with 0, then 30 ticks per second for dota, variable for CSGO)
   varInt32 size of message data
   bytes message data (snappy compressed, if indicated by flag)
}
```

When trying to think of it analytically, it would certainly possible to somehow implement a `ProtoSource` that can snappy decompress the next data "on the fly", but it's questionable if you could really gain much more, since you already said that the instantiation of a `ProtoSource` per parseable byte array should not amount to much.

After all, as already established, a replay contains much more complex data, and especially the entity decoding (Entities are the things that move around in the game, player controlled heroes, NPCs, buildings, basically everything that is relayed to the client in their game is a "networked entity"). They use a proprietary encoding for that based on BitStreams, and it seems that it is simply the case that that consumes so much, that the gains gotten here do not amount to much in comparison.

Not to diminish what you achieved! It's a great project, and when I envision HebiRobotics as getting shitloads of sensor data over the network, it's really awesome that you managed to speed it up that much!

**Comment by ennerf** [comment]
Ok. Thanks for your suggestions! Sorry the bottleneck is somewhere else. I'd recommend running Java Flight Recorder (a really good profiler bundled with the JDK) to see where your performance problems come from before you start diving into micro-optimizations.

If Snappy turns out to be the bottleneck, you might want to take a look at [Netty's Snappy](https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/compression/Snappy.java) implementation.

If the bottleneck is in decoding individual standalone entries, the easiest gain would probably come from multi-threading. I have another library for reading `.mat` files [MFL](https://github.com/HebiRobotics/MFL) where compressed entries are forward to a thread pool [thread pool](https://github.com/HebiRobotics/MFL/blob/main/mfl-core/src/main/java/us/hebi/matlab/mat/format/Mat5Reader.java#L275-L306), although in your case you probably have a lot more and smaller entries, so might want to do something smarter. I'd imagine a [Disruptor ](https://github.com/LMAX-Exchange/disruptor) setup with sharded decompression could work well.

Good luck!

**Comment by spheenik** [comment]
The thing is, there are no performance problems. I extensively optimized the parser, to the point where I simply could not find any more areas to optimize. When I did the reverse engineering needed to support Source 2 back in 2017 (iirc), the guy I was working with built a parser in C++, and while mine is still slower, it's really not that much. So my quest for optimization is just because I'm such a sucker for performance.

Going parallel is not really an option in it's current state, something like that would amount to a complete rewrite, and it is not so much of importance that one replay gets parsed the fastest possible, but that one run on a single core takes the minimal amount.

There are people that are running my parser on a farm of 20 or so nodes (full time) that parse the replays of all the games that are played online.

So when stumbling over your (I assume) announcement of QuickBuffers on Reddit in r/java, I just thought I'd have a look if like this I can squeeze out a bit somewhere. 

Was a fun ride nonetheless, and I even found a bug. And I'm more knowledgeable than before. I have another project at the moment that I use Protobuf for. One thing I realized is that the code you generate is really much more concise and compiles much quicker than what Google's version puts out.

And I like your version of `readVarInt32()`! If you don't mind, I'll copy it (with mentioning you of course)!

**Comment by ennerf** [comment]
Well, thanks for the comments and I'm glad you had fun ;) Clarity seems like a nice project. The streaming market really took off right after I stopped playing games.

> So my quest for optimization is just because I'm such a sucker for performance.

I definitely know that feeling 👍 This whole project was one giant fun performance tuning playground.

>  One thing I realized is that the code you generate is really much more concise and compiles much quicker than what Google's version puts out.

The main classes are probably pretty similarly sized, but I don't need to generate the `MessageOrBuilder` interfaces, the `Builder` types, and the entire reflection API. The Protobuf runtime library is also enormous.

I tried comparing Protobuf-Java's generated class for the conformance tests, but IntelliJ has a 2MB limit and the generated file was 6MB or so...

> And I like your version of readVarInt32()! If you don't mind, I'll copy it (with mentioning you of course)!

If you are referring to [ProtoSource::readVarint32/64](https://github.com/HebiRobotics/QuickBuffers/blob/main/runtime/src/main/java/us/hebi/quickbuf/ProtoSource.java#L802-L880), it is just a refactored version of Protobuf-Java's [CodedInputStream::readRawVarint32/64](https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/CodedInputStream.java#L978-L1118). IMO using named constants makes it easier to comprehend.

**Comment by spheenik** [comment]
> I tried comparing Protobuf-Java's generated class for the conformance tests, but IntelliJ has a 2MB limit and the generated file was 6MB or so...

Tell me about it :-)
There is a [way to up the limit](https://stackoverflow.com/questions/23057988/file-size-exceeds-configured-limit-2560000-code-insight-features-not-availabl), which I used a lot, but it makes Intellij slow...

> If you are referring to [ProtoSource::readVarint32/64](https://github.com/HebiRobotics/QuickBuffers/blob/main/runtime/src/main/java/us/hebi/quickbuf/ProtoSource.java#L802-L880), it is just a refactored version of Protobuf-Java's [CodedInputStream::readRawVarint32/64](https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/CodedInputStream.java#L978-L1118). IMO using named constants made it easier to comprehend.

I see. Did you make sure, that in your code, the contants are not looked up on the class, but instead folded like in Google's code?

**Comment by ennerf** [comment]
> I see. Did you make sure, that in your code, the constants are not looked up on the class, but instead folded like in Google's code?

Yes, static final fields are trusted and get replaced, e.g., https://shipilev.net/jvm/anatomy-quarks/15-just-in-time-constants/. In my benchmarks my version was actually a tiny bit faster, so I'm not sure whether the constants in Google's version get properly folded.
