### ISSUE TITLE
Invalid generated code for message with attribute named "quick"

### ISSUE THREAD

**Issue by cmuramoto** [HebiRobotics/QuickBuffers#41]
I tried to re-generate my classes using QuickBuffers, but it generates a duplicated method when the message has a field labeled "quick".

**Reproducer**:

src/main/resources/test.proto

```proto
syntax = "proto3";

package test;

option java_package = "test";
option optimize_for = SPEED;
option java_multiple_files = true;

message fail {
  bool quick = 1;
}

```

Java class:

```java
// Code generated by protocol buffer compiler. Do not edit!
package test;

import java.io.IOException;
import us.hebi.quickbuf.FieldName;
import us.hebi.quickbuf.InvalidProtocolBufferException;
import us.hebi.quickbuf.JsonSink;
import us.hebi.quickbuf.JsonSource;
import us.hebi.quickbuf.MessageFactory;
import us.hebi.quickbuf.ProtoMessage;
import us.hebi.quickbuf.ProtoSink;
import us.hebi.quickbuf.ProtoSource;

@SuppressWarnings("hiding")
public final class fail extends ProtoMessage<fail> implements Cloneable {
    // ... other methods, ctor, etc
    public fail clearQuick() {
        bitField0_ &= ~0x00000001;
        quick = false;
        return this;
    }

    // ... other methods
    @Override
    public fail clearQuick() {
        if (isEmpty()) {
            return this;
        }
        cachedSize = -1;
        bitField0_ = 0;
        return this;
    }
}
```

**Comment by cmuramoto** [comment]
Personally, I wouldn't choose 2 because I have a huge C codebase that shares proto files with Java. Denying the field name would force me to relabel the field and it would be a pain in the C side of the story.

Even though I can't think of any other field names that would clash with superclass methods, option 3 seems the most correct approach, despite breaking existing code, because it would keep the clear<Field> naming convention similar to vanilla protobuf, as opposed to a mangling scheme such as 1.

**Comment by ennerf** [comment]
I found a few more naming collisions wrt

* `unknown_bytes` -> `getUnknownBytes()`
* `missing_fields` -> `getMissingFields()`
* `quick` -> `clearQuick`
* `serialized_size` -> `getSerializedSize()`
* `cached_size` -> `getCachedSize()`

For now I'm just appending the field number (1) for backwards compatibility reasons. This may change in the next breaking update. Thanks for reporting.
