### ISSUE TITLE
Generate descriptor member

### ISSUE THREAD

**Issue by PeterJohnson** [HebiRobotics/QuickBuffers#47]
Would it be possible to add an option to embed the descriptor in the generated code (e.g. with a `public static final byte[] descriptor = { ... }` or similar?  For my use case, I want to log/publish the descriptor contents (separately from the data) to enable introspection with independently developed analysis tools.

**Comment by PeterJohnson** [comment]
For my use case, I don't need polymorphic access; my current implementation does a static block global registration, so the static method should work great.

I think unstripped is probably fine for me, as long as the main protobuf libraries can read it, I don't need an exact 1:1 match.

**Comment by ennerf** [comment]
v1.3 has an opt-in flag for generating `Message::getDescriptorProtoBytes()`

**Comment by PeterJohnson** [comment]
Follow-up on this: I'm trying to figure out how to actually use the per-protobuf DescriptorProto. It seems like what the reflection APIs actually work with is the *File*DescriptorProto (for each .proto file).  Can this be added in a similar way?
