### ISSUE TITLE
Accessor for name string

### ISSUE THREAD

**Issue by PeterJohnson** [HebiRobotics/QuickBuffers#52]
For my application, it would be nice to have a way to get the full name string (the fully-qualified name of the message type, scope delimited by periods) at runtime in addition to the descriptor data.  This is embedded into the binary descriptor data but is difficult to extract.  Generation wise this could probably be lumped together with the generate descriptors option, and be named something like getDescriptorName() or getDescriptorFullName()?

**Comment by ennerf** [comment]
What is the equivalent for getting the full name in the protobuf-Java API? I'm pretty sure the generator already knows the correct id, but it'd be good to have some ground-truth unit tests for confirmation.

**Comment by PeterJohnson** [comment]
Message.getDescriptor() (or getDescriptorForType()) .getFullName().

**Comment by ennerf** [comment]
Thanks. I'm currently extremely busy, so I probably won't get to it until last week at the earliest

**Comment by ennerf** [comment]
fixed by #57
