### ISSUE TITLE
Suggestions for Utf8String - hashCode and CharSequence

### ISSUE THREAD

**Issue by cjoc-gs** [HebiRobotics/QuickBuffers#56]
We have a couple of use cases which would be helped by a couple of small tweaks to Utf8String:

- **Using Utf8String as a map key**. We need to translate from an internal string format to an external one. There is a small universe of possible values, and translation is comparatively expensive, so it makes sense to cache the internal -> external mapping. Ideally we'd do this like so:

  ```Java
  Utf8String internalFormat = protoMessage.getA();
  if (!internal2ExternalMap.contains(internalFormat)) {
      internal2ExternalMap.put(internalFormat.clone(), Translator.translate(internalFormat));
  }
  CharSequence externalFormat = internal2ExternalMap.get(internalFormat);
  ```
  Which does work right now. However, because `Utf8String` just returns 0 for `hashCode`, all keys fall into the same bucket, meaning lookups are expensive. <br>
  Our use case calls for zero allocations, so we can't index the map on `String`, because we need to avoid calling `Utf8String::getString`.<br>
  Keying using mutable objects is of course inherently fragile, but we're resigned to the fact our zero-allocation environment makes _some_ fragility justifiable, or perhaps inevitable.

- **Writing to a target which only accepts CharSequence**. Once again, because we can't use `getString`, the only option is to keep a `StringBuilder` to hand, call `Utf8String::getChars` and pass that to the target. However, it would be nice to avoid that additional copy.

Currently we've achieved both of these by writing a wrapper around `Utf8String`, which implements `CharSequence` and `hashCode`. However it would be nice if we could fold this functionality into `Utf8String` itself.

Would you be amenable to such a change? Can see the ideological case for short-circuiting `hashCode` for totally mutable objects; but maybe we could make it an optional protoc arg? To implement CharSequence also feels achievable.

Happy to take a stab at it myself, with your blessing.

Cheers

**Comment by ennerf** [comment]
I'm not opposed to putting some amount of burden on the user, but including mutable values in a hash code is a recipe for disaster. That'd definitely result in user errors that are incredibly hard to debug.

You should be using `Utf8String::getString(Utf8Decoder)` method, which allows you to specify a custom [Utf8Decoder ](https://github.com/HebiRobotics/QuickBuffers/blob/cc550d94c1abb808b9143d6421bc4ab1a08f70da/runtime/src/main/java/us/hebi/quickbuf/Utf8Decoder.java#L29) to go from `byte[]` to `String`.

Here is an example for a custom [StringCache](https://gist.github.com/ennerf/08c0dbc6d0af8eb4487ef1d182f37ce7). Depending on the amount and importance of data integrity you'd probably also want to add a char comparison after a cache hit.

**Comment by cjoc-gs** [comment]
Thanks. That `StringCache` is nice - more idiomatic, and probably more performant, than the wrapper we've written. Thanks for the suggestion.

Do you have any thoughts on implementing `CharSequence`?

**Comment by ennerf** [comment]
`Utf8String` wouldn't be able to implement `CharSequence` directly because it's `utf8` and the data would have to be parsed to get the character mapping required for `charAt(index)`. At that point you might as well go through StringBuilder.

However, you already have access to the raw bytes. If you can guarantee that your system only has to handle Ascii data then it'd be fairly simple to write a tiny wrapper over the raw byte data.
