### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by liangsir12** [HebiRobotics/QuickBuffers#61]
When I want to apply QuickBuffers to accelerate JSON conversion, I don't know how to automatically generate both Google's Java files and QuickBuffers' Java files instead of manually generating them. Can this parameter replace_package avoid conflicts? How should I do it.

**Comment by ennerf** [comment]
Here is an example for generating the [tests](https://github.com/HebiRobotics/QuickBuffers/blob/8908d8937f9adff22f41bdcdf6bf858c86f280b2/runtime/pom.xml#L184)

```
replace_package=(protobuf)=quickbuf
```

generates all QuickBuffers messages as `com.google.quickbuf.something` instead if `com.google.protobuf.something`. You can use full on Regex if you want to get fancy.
