### ISSUE TITLE
Publish generator jar to maven?

### ISSUE THREAD

**Issue by brendo-m** [HebiRobotics/QuickBuffers#64]
First of all thanks for this project! We are exploring migrating to it and have seen some great improvements in just a little testing so are very excited about it.

Would it be possible to publish the generator package jar to maven please? We use bazel as our build tool and so it's difficult to use the executables published to `protoc-gen-quickbuf`, but trivial to run `us.hebi.quickbuf.generator.CompilerPlugin` as a java binary. I've proven this works with a local build.

Thanks!

**Comment by ennerf** [comment]
How are you calling protoc with a Java process? Generating the necessary scripts is typically a huge pain.

Do you need the shaded version that includes all dependencies, or just the basic project w/ specified dependencies?

**Comment by brendo-m** [comment]
> How are you calling protoc with a Java process?

We use this [bazel library](https://github.com/stackb/rules_proto) which handles all that and all that's needed to add a plugin is to point at the main class.

> Do you need the shaded version that includes all dependencies, or just the basic project w/ specified dependencies?

Shaded version would be easier but we can make either work

**Comment by ennerf** [comment]
I published the generator artifact, but nothing is showing up. Maybe the main repo is having some issues at the moment. I'll try again another day.

**Comment by brendo-m** [comment]
Happy new year! Did you figure out the issue here?

**Comment by ennerf** [comment]
It still doesn't show up. Unfortunately, the partly manual release process I currently have is becoming bothersome with the increasing use of the library. Luckily Github finally added macOS arm64 runners, but I need to spend some time to refactor and automate everything.

**Comment by ennerf** [comment]
The generator jar and the shaded version for `1.4` were uploaded to maven central. Here is a confirmation:

![image](https://github.com/HebiRobotics/QuickBuffers/assets/5491587/5833d71e-d0de-4964-8b0e-66cfeb1c109f)
