### ISSUE TITLE
ConformanceQuickbufTest failure on JDK8, Tag 1.3.3

### ISSUE THREAD

**Issue by yinfeifan** [HebiRobotics/QuickBuffers#67]
[ERROR] Failures:
[ERROR]   ConformanceQuickbufTest.testValidDataRepeatedEnumPacked:45->assertEqualsProto2:77 Recommended.Proto2.ProtobufInput.ValidDataRepeated.ENUM.PackedInput.PackedOutput.ProtobufOutput: arrays first differed at element [10]; expected:<-1> but was:<-113>

**Comment by ennerf** [comment]
Conformance tests on CI run as expected. Closing because I can't reproduce it.
