### ISSUE TITLE
Cannot generate java file with google proto Any, timestamp

### ISSUE THREAD

**Issue by hunghoang** [HebiRobotics/QuickBuffers#69]
Hi
I have my file: 
`syntax = "proto3";

package models;
option java_package = "models";

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";
...
`
But when generating java file:
` protoc-quickbuf --quickbuf_out=indent=4,allocation=lazy,extensions=embedded:src/main/java src/main/resources/models.proto`
, I got these error:
google/protobuf/any.proto: File not found.
google/protobuf/timestamp.proto: File not found.
...models.proto:6:1: Import "google/protobuf/any.proto" was not found or had errors.
...models.proto:7:1: Import "google/protobuf/timestamp.proto" was not found or had errors.

How could I generate file with  Any and Timestamp

**Comment by hunghoang** [comment]
ah, ok, let me try it
Many thanks

**Comment by ennerf** [comment]
I added a link in the Readme to make it more clear. Note that the JSON representations for e.g. Timestamp are not special-cased and currently do not match Protobuf-Java's.
