### ISSUE TITLE
Change ProtoMessage from an abstract class to an interface

### ISSUE THREAD

**Issue by xpromache** [HebiRobotics/QuickBuffers#70]
Hello,

I'm looking to write a manual encoder for a regular java class such that I can use the objects of that class inside the proto generated classes. I want to do that for one specific class which has a lot of objects in order to avoid creating proto copies of those  objects (they are structured in a hierarchy so I cannot easily use a proto object instead of the plain java ones).

Do you think it is possible to change ProtoMessage to be an interface and change the current ProtoMessage into AbstractProtoMessage which the generated messages will inherit?

Then I can implement the ProtoMessage interface on my own class.  I will also need to find a way for the generated messages to refer to my non generated ProtoMessage class.

thanks!

**Comment by He-Pin** [comment]
Abstract class is faster

**Comment by xpromache** [comment]
> Abstract class is faster

Is there a significant difference?

Are there some instructions on how to run the benchmarks?
I would like to give it a try to see the difference between the interface and abstract class.

**Comment by xpromache** [comment]
Ok, so I managed to run a benchmark I don't see much of a difference:

```
Original version 1.4
Benchmark                                             Mode  Cnt      Score     Error   Units
SbeThroughputBenchmarkQuickbuf.testCarDecode         thrpt   10   6430.948 ± 133.668  ops/ms
SbeThroughputBenchmarkQuickbuf.testCarEncode         thrpt   10   6151.960 ±  54.445  ops/ms
SbeThroughputBenchmarkQuickbuf.testCarEncodeFast     thrpt   10   7597.045 ±  61.143  ops/ms
SbeThroughputBenchmarkQuickbuf.testCarEncodeJson     thrpt   10   1618.724 ±  24.920  ops/ms
SbeThroughputBenchmarkQuickbuf.testMarketDecode      thrpt   10  17996.138 ± 184.772  ops/ms
SbeThroughputBenchmarkQuickbuf.testMarketEncode      thrpt   10  19474.978 ±  49.664  ops/ms
SbeThroughputBenchmarkQuickbuf.testMarketEncodeFast  thrpt   10  26539.481 ±  68.114  ops/ms
SbeThroughputBenchmarkQuickbuf.testMarketEncodeJson  thrpt   10   4867.762 ±  51.673  ops/ms



Modified version with ProtoMessage implementing an interface
Benchmark                                             Mode  Cnt      Score     Error   Units
SbeThroughputBenchmarkQuickbuf.testCarDecode         thrpt   10   6547.152 ±  92.168  ops/ms
SbeThroughputBenchmarkQuickbuf.testCarEncode         thrpt   10   6491.842 ± 129.741  ops/ms
SbeThroughputBenchmarkQuickbuf.testCarEncodeFast     thrpt   10   7852.626 ±  97.374  ops/ms
SbeThroughputBenchmarkQuickbuf.testCarEncodeJson     thrpt   10   1656.724 ±   6.130  ops/ms
SbeThroughputBenchmarkQuickbuf.testMarketDecode      thrpt   10  18267.815 ± 237.863  ops/ms
SbeThroughputBenchmarkQuickbuf.testMarketEncode      thrpt   10  16333.160 ± 169.802  ops/ms
SbeThroughputBenchmarkQuickbuf.testMarketEncodeFast  thrpt   10  26920.955 ± 198.330  ops/ms
SbeThroughputBenchmarkQuickbuf.testMarketEncodeJson  thrpt   10   4862.220 ± 120.751  ops/ms
```

The modified code is here:
https://github.com/xpromache/QuickBuffers

Because I didn't want to modify the proto generator, I created  an interface ProtoMessageIf and changed all the references in the runtime to this interface.

**Comment by ennerf** [comment]
> I'm looking to write a manual encoder for a regular java class such that I can use the objects of that class inside the proto generated classes

I'm not clear on the issue. Can you provide a simplified code example for a fictional proto definiton and a Java class that interact in the way you imagine?

You can already use `ProtoSource` and `ProtoSink` from classes that do not inherit from `ProtoMessage`.

**Comment by xpromache** [comment]
I have a java class  ParameterValue which appears in many protobuf messages that are  sent via an api.
Currently I declared a protobuf message by the same name "ParameterValue" and each time I want to build one of those api messages, I convert all my java ParameterValue to the protobuf variant which can be inserted in the API messages.

Here is some of the api messages:
https://github.com/yamcs/yamcs/blob/master/yamcs-api/src/main/proto/yamcs/protobuf/processing/processing.proto

That conversion from java to protobuf makes lots of garbage and it also eats up CPU so I thought I could get rid of it if I could use my java ParameterValue inside the protobuf messages, directly without conversion.

Finally the ProtoSink will be used on the api message but when it serializes the members of type ParameterValue it will call the methods which I handcode.

**Comment by ennerf** [comment]
Out of curiosity, are you using grpc with QuickBuffers? Does that work well? I've never looked into it.

I assume you can't use the generated proto class directly because you need some more advanced logic? A common way to do this would be a small facade that provides a nicer API and translates to and from proto values. Another would be to auto-generate translations with [MapStruct](https://mapstruct.org/) or a custom protobuf plugin.

I think the manual marshalling you're trying to do would be very error prone and comparatively hard to maintain. I've done this myself for some very small specialized messages, but even for those the occasional updates were pretty difficult.

**Comment by xpromache** [comment]
I'm not using grpc and not using QuickBuffers either. I am using google protobuf with a kind of custom grpc like service layer. 
I was looking to implement my manual marshalling idea with google protobuf but got entangled into the myriad of protobuf builders and mess so I ended up looking for alternatives to protobuf.

(I was anyway unhappy for a long time that the jar of my java core classes is 3.4MB, another jar of a web client which includes an extensive Angular app is 2.9MB and the jar of the generated protobuf crap is 6.3MB)

So the facade you mention is what I'm doing now but I wanted to explore the gains I can obtain by not doing the intermediate protobuf objects for that particular class. The class rarely changes if ever and if it changes I have to change the facade anyway.

**Comment by ennerf** [comment]
Before you implement the marshalling yourself I think you should try replacing protobuf-java with QuickBuffers in your current code. That should already fix your issues with performance & memory allocations and the misaligned builder API.

If that is not enough, you could also define your message fields as `byte` or `repeated byte` with lazy custom marshalling. The `byte` type is compatible with `message`, but QuickBuffers would not attempt to interpret the bytes. It'd get you the same result without any API changes.

Lastly, I'm not opposed to adding an extra interface, but I'm not a fan of the resulting naming. I'd prefer `ProtoMessage` being an interface w/ an `AbstractProtoMessage` base class, but that'd be a breaking change. I would want to think a bit more about it and also go through the potential changes needed to support the new `Protobuf-Editions` format.

**Comment by xpromache** [comment]
Hey thanks for your feedback. 
How will the lazy custom marshaling work?

if I currently have:

```
message x {
   repeated ParameterValue values = 1;
}
```

how would I replace that with the `repeated byte` to get the custom marshalling?

As for the naming of the interface, my suggestion was indeed to turn ProtoMessage into an interface with an AbstractProtoMessage as base for the generated classes (this is actually also what google protobuf does but then that interface is not used much, they require the abstract class everywhere), and this is indeed a breaking change.
In my little performance test I introduced ProtoMessageIf because I did not want to change the generator.

**Comment by ennerf** [comment]
I'd have to look up the exact code, but it'd be something like

```proto
message x {
   repeated bytes values = 1;
}
```

with parsing

```Java
var valueBytes = x.getValues().get(i);
var source = ProtoSource.newInstance(bytes);
var valueMsg = ParameterValue.parseFrom(source);
```

All objects are reusable, so it can be done without any allocations.

**Comment by ennerf** [comment]
Did that solve your issue?

**Comment by xpromache** [comment]
I didn't implement it, I need to get some courage to get started because it's a big change.

We can close the issue for now but if you want in the future to introduce some breaking changes into QuickBuffers maybe you can consider also my suggestion with the interface.
