### ISSUE TITLE
protoc-gen-quickbuf link is broken in release

### ISSUE THREAD

**Issue by spacey-sooty** [HebiRobotics/QuickBuffers#71]
It redirects to protoc-gen-request

**Comment by ennerf** [comment]
Sorry for the delay. I somehow didn't get a notification about this issue.

Can you add more details? Is this about a link in the Readme, or about a wrong maven central or binary release?

**Comment by spacey-sooty** [comment]
On the releases tab when I clicked on the most recent release and clicked the links to protoc-gen-quickbuf and protoc-gen-request it would send to the same link. Tried it again appears to be fixed mbe I was just tired and clicking the wrong thing :laughing:
