### ISSUE TITLE
InRelease PGP signature uses weak algorithm

### ISSUE THREAD

**Issue by PeterJohnson** [HebiRobotics/QuickBuffers#73]
Getting the following warning from apt:

```
W: https://github.com/HebiRobotics/QuickBuffers/releases/latest/download/./InRelease: Signature by key C9B29D476D15980F7D7824A9C6C4CC6251061FB4 uses weak algorithm (nistp256)
```

**Comment by ennerf** [comment]
@mikehearn the release was [built with v13.1](https://github.com/HebiRobotics/QuickBuffers/blob/main/.github/workflows/release.yml#L176). Did this by any chance already get addressed in one of the more recent versions?

**Comment by mikehearn** [comment]
The warning is incorrect, see here:

https://discourse.ubuntu.com/t/new-requirements-for-apt-repository-signing-in-24-04/42854/19

They are planning to remove the warning again.

**Comment by PeterJohnson** [comment]
Thanks, I’ll wait for that fix.  Closing.
